# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e3610c8f9dbdf3fd10ec0f2c946d4dfb3df8a3734a7f03ab9318dc9f9d45c5b26b90c75f8cb494fc7adbb152d2ddf39e67db75daad81d7436d7c3345dc3295d

test:
  secret_key_base: 6ed93026e9cccf34a46c9dbe3b71d383125dd688ad2f7fc1d14a2b69020aabc823de770c9d6ec1ad6d7f2e05a4b51bfede050c1ae299058ba560558b55cfb417

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
